w23/xash3d-fwgs

ref_vk/wscript, scripts/waifulib/glslc.py
Написал glslc модуль. Устанавливает пока всё в valve, когда-нибудь потом надо будет придумать как зашивать внутрь самого ref_vk.
Оставил в комментариях что можно менять. Предложения принимаются :)
=> waf: add glslc module

ref_vk/vk_framectl.c, ref_vk/vk_framectl.h, ref_vk/vk_pipeline.c, ref_vk/vk_render.c, ref_vk/vk_render.h, ref_vk/vk_rtx.c
new command is `vk_rtx_toggle`
=> rtx: add runtime toggle between ray tracing and traditional renderer

.github/workflows/c-cpp.yml, ref_vk/TODO.md, ref_vk/vk_beams.c, ref_vk/vk_brush.c, ref_vk/vk_framectl.c, ref_vk/vk_ray_model.c, ref_vk/vk_render.c, ref_vk/vk_render.h, ref_vk/vk_scene.c, ref_vk/vk_sprite.c, ref_vk/vk_studio.c
this simplifies the api and implementation
=> join alloc+lock operations on buffer init

ref_vk/TODO.md, ref_vk/shaders/ray.rchit, ref_vk/shaders/ray.rgen, ref_vk/shaders/ray_common.glsl, ref_vk/shaders/ray_interop.h, ref_vk/shaders/ray_kusochki.glsl, ref_vk/vk_beams.c, ref_vk/vk_brush.c, ref_vk/vk_core.h, ref_vk/vk_framectl.c, ref_vk/vk_framectl.h, ref_vk/vk_light.c, ref_vk/vk_light.h, ref_vk/vk_ray_internal.h, ref_vk/vk_ray_model.c, ref_vk/vk_render.c, ref_vk/vk_render.h, ref_vk/vk_rmain.c, ref_vk/vk_rtx.c, ref_vk/vk_sprite.c, ref_vk/vk_studio.c
also add a lot of observations to ref_vk/TODO.md related to materials
=> fix depth test for glow render mode; comments

ref_vk/shaders/ray.rgen
=> attenuate area lights by projected area, fix #46

README.md, engine/client/cl_game.c, engine/common/build.c, engine/ref_api.h, engine/server/server.h, engine/server/sv_client.c, engine/server/sv_cmds.c, engine/server/sv_log.c, engine/server/sv_main.c, public/build.h, ref_gl/gl_context.c, ref_soft/r_context.c, ref_vk/vk_rmain.c, ref_vk/vk_scene.h, ref_vk/vk_sprite.c
Had to upgrade RefAPI, since engine expects it's R_WorldToScreen but we're using TriWorldToScreen in RefAPI. The main difference is that TriWorldToScreen adds viewport coordinates to the result.
Also made ref_vk use and export real WorldToScreen rather than a stub. :)
=> Sync with upstream

ref_vk/shaders/ray.rchit
Fixes #167 (this time for real :-)). The original function did not
account for anisotropy, so use code from a different paper.
=> Compute texcoord gradients with anisotropy.

ref_vk/shaders/ray.rchit
=> Pass world positions to computeAnisotropicEllipseAxes().

ref_vk/vk_light.c
=> rtx: do not treat SURF_SKY as light source

ref_vk/camera.c, ref_vk/shaders/ray.rgen, ref_vk/vk_beams.c, ref_vk/vk_brush.c, ref_vk/vk_light.c, ref_vk/vk_mapents.c, ref_vk/vk_mapents.h, ref_vk/vk_materials.c, ref_vk/vk_ray_model.c, ref_vk/vk_render.h, ref_vk/vk_scene.c, ref_vk/vk_sprite.c, ref_vk/vk_textures.c
example:
```
{
"_xvk_surface_id" "489"
"_xvk_texture" "#maps/test_material.bsp:debug_normal1.mip"
}
```
if _xvk_texture is empty, then the surface will be deleted
surfaces can be deleted or their
=> rtx: enable patching surface textures

ref_vk/vk_brush.c
=> fix incorrect surface indexing when patching

ref_vk/vk_cvar.c, ref_vk/vk_cvar.h, ref_vk/vk_framectl.c, ref_vk/vk_rtx.c
Remove requirement -vkdebug for vk_rtx_reload, vk_rtx_reload_rad, vk_rtx_freeze; fix #68
Add vk_rtx command, fix #67
=> Improved console commands 

ref_vk/vk_materials.c
=> Add new location for materials.mat

ref_vk/vk_rtx.c
=> Add reload 2d pipeline

engine/common/cvar.c, ref_vk/vk_cvar.c, ref_vk/vk_cvar.h, ref_vk/vk_framectl.c
Здесь часть улучшения для #246 и #121.
=> cvar improvements

ref_vk/vk_brush.c, ref_vk/vk_mapents.c, ref_vk/vk_mapents.h, ref_vk/vk_materials.c, ref_vk/vk_scene.c, ref_vk/vk_textures.c, ref_vk/vk_textures.h
Implemented blindly on a machine w/o RT extensions, so cannot test whether it works. Will test later.
fixes #291
=> rtx: allow creating new pbr materials

ref_vk/camera.c, ref_vk/vk_brush.c, ref_vk/vk_brush.h
1. include correct current texture
2. print animation chain info
relevant for #301
=> respect animated textures in ui_infotool

ref_vk/vk_materials.c
use it like this:
```materials.mat
{
"include" "other.mat"
"include" "another.mat"
// ...
}
// continue with regular material definitions
```
```other.mat
{
// can also nest includes (up to 4)
"include" "yetanother.mat"
}
// continue with definitions as usual
{
// may also have includes later too
"include" "whatever.mat"
}
// ...
```
etc
fixes #312
=> rtx: add include support for materials

ref_vk/infotool.c, ref_vk/shaders/ray_interop.h, ref_vk/vk_const.h, ref_vk/vk_light.c, ref_vk/vk_rtx.c, ref_vk/vk_scene.c
Just increase point lights limit per light cell.
Also:
- update infotool to show point lights info
- move light cluster finalization to vk_scene to make sure infotool has
the recentmost data
#279
=> rtx: fix missing flashlight in c1a4i

common/render_api.h, engine/client/cl_tent.c, ref_vk/vk_light.c, ref_vk/vk_light.h, ref_vk/vk_render.c, ref_vk/vk_rmain.c, ref_vk/vk_scene.c
#148
Скриншоты:
Взаимодействие фонарика с монтировкой требует разбирательство работы материалов вблизи света. 
~~Классический рендер тоже закостылял (#88):~~
(пришлось отменить)
=> new flashlight

ref_vk/vk_brush.c, ref_vk/vk_light.h, ref_vk/vk_ray_model.c, ref_vk/vk_render.h
=> rt: assoc dyn polylights w/ render model

ref_vk/shaders/denoiser.comp, ref_vk/shaders/ray_primary.rchit
Больше не ломает слишком тёмные текстуры.
=> more correct base_color processing

ref_vk/vk_swapchain.c
=> vk: recreate swapchain on exclusive mode lost, fix #365

ref_vk/vk_light.c
=> rt: fix point light cluster crash on missing pvs

ref_vk/vk_swapchain.c
Unless we know the error is unrecoverable, try to recreate swapchain anyway. Fixes #375
=> vk: recreate swapchain on all errors except fatal

engine/client/ref_common.c
=> fix incorrect display device id in r_show_devices (R_GetRenderDevices_f)

ref_vk/profiler.h, ref_vk/vk_materials.c, ref_vk/vk_textures.c
Most of the time was spent doing printfs kekw.
Also add load stats and timings.
=> Make materials load 2x faster

ref_vk/sebastian.py
support //comment and /* comment */
and autofix comma
=> added support comments for rt.json

ref_vk/sebastian.py, ref_vk/wscript, scripts/waifulib/sebastian.py
=> integrate sebastian with ci

ref_vk/TODO.md, ref_vk/shaders/ray_common_alphatest.rahit, ref_vk/shaders/ray_primary.comp, ref_vk/shaders/ray_primary.rgen, ref_vk/shaders/ray_primary_common.glsl, ref_vk/shaders/ray_primary_hit.glsl, ref_vk/shaders/rt.json, ref_vk/shaders/rt_geometry.glsl, ref_vk/vk_rtx.c
Makes it work under open source mesa amdgpu driver (although it's ~30% slower than the old binary driver)
=> Convert primary ray pass to compute shader

ref_vk/shaders/bounce.comp, ref_vk/shaders/denoiser.comp, ref_vk/shaders/light.glsl, ref_vk/shaders/light_common.glsl, ref_vk/shaders/light_polygon.glsl, ref_vk/shaders/ray_light_direct.glsl, ref_vk/shaders/ray_primary.comp, ref_vk/shaders/ray_primary_hit.glsl, ref_vk/shaders/rt.json, ref_vk/shaders/trace_additive.glsl
=> Add indirect illumination

ref_vk/shaders/bounce.comp, ref_vk/shaders/ray_primary.comp, ref_vk/vk_ray_model.c
Do translucency in bounce stage. It's not great, but lets us see thing through.
Also fix reading OOB uninitialized memory for color/alpha.
=> rt: add alpha-quality alpha blending

ref/vk/shaders/denoiser.comp, ref/vk/shaders/ray_primary_hit.glsl, ref/vk/shaders/trace_additive.glsl, ref/vk/vk_beams.c, ref/vk/vk_brush.c, ref/vk/vk_brush.h, ref/vk/vk_common.h, ref/vk/vk_ray_model.c, ref/vk/vk_render.c, ref/vk/vk_render.h, ref/vk/vk_renderstate.h, ref/vk/vk_rmain.c, ref/vk/vk_rtx.h, ref/vk/vk_scene.c, ref/vk/vk_sprite.c, ref/vk/vk_sprite.h, ref/vk/vk_studio.c, ref/vk/vk_studio.h
=> Improve blending modes

ref/vk/shaders/additive.rahit, ref/vk/shaders/alphamask.rahit, ref/vk/shaders/brush.frag, ref/vk/shaders/brush.vert, ref/vk/shaders/light_common.glsl, ref/vk/shaders/ray_kusochki.glsl, ref/vk/shaders/rt_geometry.glsl, ref/vk/shaders/trace_additive.glsl, ref/vk/shaders/utils.glsl, ref/vk/vk_beams.c, ref/vk/vk_brush.c, ref/vk/vk_geometry.h, ref/vk/vk_render.c, ref/vk/vk_rmain.c, ref/vk/vk_rpart.c, ref/vk/vk_rpart.h, ref/vk/vk_sprite.c, ref/vk/vk_studio.c, ref/vk/vk_triapi.c, ref/vk/vk_triapi.h
=> Moar beams

ref/vk/vk_previous_frame.c, ref/vk/vk_ray_model.c, ref/vk/vk_render.c, ref/vk/vk_studio.c
Right way to put previous model matrix
Fix bad index of previous frame
Fallback to current frame if previous frames are outdated
=> vk rt: fix reprojection

ref/vk/vk_math.c, ref/vk/vk_math.h, ref/vk/vk_studio.c
Enables applying normal maps to studio models.
Fixes #220, fixes #241
=> rt: compute tangents for studio models

ref/vk/data/valve/luchiki/maps/c0a0e.bsp.patch, ref/vk/data/valve/luchiki/maps/c1a0a.bsp.patch
Моя немного поправил забытое освещение в лифте (хак я удалил, а выставить освещение забыл), ну и у вагончика немного поправил акцент.
=> Update lighting patches

ref/vk/vk_brush.c, ref/vk/vk_brush.h, ref/vk/vk_light.c, ref/vk/vk_light.h, ref/vk/vk_mapents.c, ref/vk/vk_mapents.h, ref/vk/vk_ray_model.c, ref/vk/vk_render.c, ref/vk/vk_render.h, ref/vk/vk_rtx.c, ref/vk/vk_scene.c, ref/vk/vk_studio.c
=> Enable live reloading light data

ref/vk/shaders/ray_primary_hit.glsl
Я подобрал новое компромиссное значение которое не требует clamp.
Это не идеально, но пока сойдёт. Может давать немного больше солнечных зайчиков чем с clamp.
Позже надо будет разобраться с самим kusok.emissive.
=> More correct emissive textures

ref/vk/vk_light.c, ref/vk/vk_ray_internal.h, ref/vk/vk_staging.c, ref/vk/vk_staging.h, ref/vk/vk_textures.c
=> Fixes made during stream E236

ref/vk/shaders/light.glsl
=> Add simple soft shadows by @LifeKILLED

ref/vk/shaders/ray_primary.comp
fixes #63
also, compute max distance based on the far plane distance
=> rt: originate ray on the near plane

ref/vk/r_speeds.c, ref/vk/r_speeds.h, ref/vk/vk_beams.c, ref/vk/vk_beams.h, ref/vk/vk_brush.c, ref/vk/vk_core.c, ref/vk/vk_framectl.c, ref/vk/vk_light.c, ref/vk/vk_light.h, ref/vk/vk_ray_accel.c, ref/vk/vk_render.c, ref/vk/vk_rmain.c, ref/vk/vk_sprite.c, ref/vk/vk_sprite.h, ref/vk/vk_staging.c, ref/vk/vk_studio.c
Per-frame counters for:
Fixes #483
=> Add various metrics to profiler display

ref/vk/r_speeds.c, ref/vk/shaders/ray_interop.h, ref/vk/shaders/ray_primary_hit.glsl, ref/vk/vk_brush.c, ref/vk/vk_core.c, ref/vk/vk_core.h, ref/vk/vk_mapents.c, ref/vk/vk_mapents.h, ref/vk/vk_materials.c, ref/vk/vk_materials.h, ref/vk/vk_ray_model.c
=> A few improvements for patches and materials

ref/vk/vk_brush.c, ref/vk/vk_combuf.c, ref/vk/vk_mapents.c, ref/vk/vk_mapents.h, ref/vk/vk_scene.c
Refactor NewMap and patch loading a bit.
=> vk: allow dynamic surface/material patching

ref/vk/shaders/ray_interop.h, ref/vk/vk_beams.c, ref/vk/vk_brush.c, ref/vk/vk_ray_model.c, ref/vk/vk_render.h, ref/vk/vk_sprite.c, ref/vk/vk_textures.c, ref/vk/vk_textures.h, ref/vk/vk_triapi.c
Also comment on various code paths to get render modes.
Related to #460
=> E256: clean up material flags

ref/vk/infotool.c, ref/vk/shaders/color_spaces.glsl, ref/vk/shaders/trace_simple_blending.glsl, ref/vk/vk_brush.c, ref/vk/vk_ray_internal.h, ref/vk/vk_ray_model.c, ref/vk/vk_render.h, ref/vk/vk_rmain.c
=> Stream E260

.github/workflows/c-cpp.yml, ref/vk/shaders/additive.rahit, ref/vk/shaders/bounce.comp, ref/vk/shaders/light_common.glsl, ref/vk/shaders/ray_interop.h, ref/vk/shaders/ray_kusochki.glsl, ref/vk/shaders/ray_primary.comp, ref/vk/shaders/ray_primary.rchit, ref/vk/shaders/ray_primary_hit.glsl, ref/vk/shaders/ray_shadow.rchit, ref/vk/shaders/rt_geometry.glsl, ref/vk/shaders/trace_simple_blending.glsl, ref/vk/vk_ray_accel.c, ref/vk/vk_ray_internal.h, ref/vk/vk_ray_model.c, ref/vk/vk_render.h, ref/vk/vk_rtx.c
=> Extract per-model data from kusochki

ref/vk/vk_brush.c, ref/vk/vk_common.h, ref/vk/vk_light.c, ref/vk/vk_logs.h, ref/vk/vk_overlay.c, ref/vk/vk_ray_model.c, ref/vk/vk_rmain.c, ref/vk/vk_studio.h, ref/vk/vk_studio_model.c, ref/vk/vk_studio_model.h, ref/vk/vk_triapi.c
=> Fixes from stream E291

ref/vk/vk_studio.c, ref/vk/vk_studio_model.c
=> Fixes made during stream E296

ref/vk/data/valve/luchiki/maps/c1a1b.patch, ref/vk/vk_brush.c, ref/vk/vk_mapents.c, ref/vk/vk_mapents.h
=> vk: patch: allow smoothing entire brush model

ref/vk/shaders/bluenoise.glsl, ref/vk/vk_textures.c, ref/vk/vk_textures.h
Это бэкпорт моего фикса для оригинального Xash3D-FWGS, сделанного в незаконченном менеджере текстур.
Чинит #532.
=> Фикс аллокаций текстур-заглушек

ref/vk/data/valve/maps/c1a0.rad, ref/vk/data/valve/maps/c1a0b.rad, ref/vk/data/valve/maps/c1a0d.rad, ref/vk/data/valve/maps/c1a0e.rad, ref/vk/data/valve/maps/c1a1a.rad, ref/vk/data/valve/maps/c1a1f.rad, ref/vk/data/valve/maps/lights.rad
Refactoring, performance improvement (more for c1a0b), minor changes
=> update rad files

ref/vk/TODO.md, ref/vk/infotool.c, ref/vk/shaders/brush.frag, ref/vk/shaders/denoiser.comp, ref/vk/shaders/ray_interop.h, ref/vk/shaders/ray_primary_hit.glsl, ref/vk/vk_core.c, ref/vk/vk_cvar.c, ref/vk/vk_cvar.h, ref/vk/vk_framectl.c, ref/vk/vk_light.c, ref/vk/vk_render.c, ref/vk/vk_rmain.c, ref/vk/vk_rtx.c, ref/vk/vk_scene.c
=> Things done during stream E324

ref/vk/TODO.md, ref/vk/shaders/bounce.comp, ref/vk/shaders/denoiser.comp, ref/vk/shaders/ray_interop.h, ref/vk/vk_brush.c, ref/vk/vk_core.c, ref/vk/vk_materials.c, ref/vk/vk_ray_model.c, ref/vk/vk_rtx.c, ref/vk/vk_scene.c
=> Things done during stream E325

ref/vk/NOTES.md, ref/vk/TODO.md, ref/vk/vk_brush.c, ref/vk/vk_brush.h, ref/vk/vk_core.c, ref/vk/vk_rmain.c, ref/vk/vk_scene.c
=> Stuff done during stream E327

ref/vk/TODO.md, ref/vk/vk_brush.c, ref/vk/vk_ray_model.c
=> E331: make water emissive again

ref/vk/TODO.md, ref/vk/shaders/noise.glsl, ref/vk/shaders/ray_interop.h, ref/vk/shaders/ray_primary_hit.glsl, ref/vk/vk_brush.c, ref/vk/vk_geometry.c, ref/vk/vk_geometry.h, ref/vk/vk_rtx.c
=> Thing done during stream E331

ref/vk/NOTES.md, ref/vk/TODO.md, ref/vk/shaders/ray_primary_hit.glsl, ref/vk/vk_brush.c, ref/vk/vk_math.c, ref/vk/vk_math.h
=> Things done during stream E332

ref/vk/TODO.md, ref/vk/vk_brush.c, ref/vk/vk_framectl.c, ref/vk/vk_mapents.c, ref/vk/vk_mapents.h, ref/vk/vk_rtx.c, ref/vk/vk_rtx.h, ref/vk/vk_scene.c
=> Things committed during streams E338-E339

ref/vk/NOTES.md, ref/vk/TODO.md, ref/vk/shaders/bounce.comp, ref/vk/shaders/denoiser.comp, ref/vk/shaders/ray_interop.h, ref/vk/shaders/ray_light_direct.glsl, ref/vk/shaders/ray_primary.comp, ref/vk/vk_brush.c, ref/vk/vk_combuf.c, ref/vk/vk_devmem.c, ref/vk/vk_ray_model.c, ref/vk/vk_render.c, ref/vk/vk_render.h, ref/vk/vk_rmain.c, ref/vk/vk_rtx.c, ref/vk/vk_rtx.h
=> Things done during stream E339

ref/vk/NOTES.md, ref/vk/TODO.md, ref/vk/shaders/denoiser.comp
=> Stuff done during stream E342

ref/vk/TODO.md, ref/vk/shaders/bounce.comp, ref/vk/shaders/denoiser.comp, ref/vk/shaders/light.glsl, ref/vk/shaders/light_polygon.glsl, ref/vk/shaders/ray_light_direct.glsl, ref/vk/shaders/ray_primary_hit.glsl, ref/vk/vk_brush.c, ref/vk/vk_render.c, ref/vk/vk_render.h, ref/vk/vk_sprite.c, ref/vk/vk_studio.c
=> Thing done during stream E345

ref/vk/vk_core.c, ref/vk/wscript
=> Improved warning when there are no ray extensions

ref/vk/vk_render.c
Use `vk_use_material_textures` cvar to show new PBR material textures for traditional rendering.
Note that they're often sampled in an incorrect colorspace, so they look different from RT.
Fixes #711
=> vk: trad: allow rendering with replaced PBR textures

ref/vk/TODO.md, ref/vk/r_textures.c, ref/vk/shaders/bounce.comp, ref/vk/vk_rtx.c
=> Stuff done during stream E350

ref/vk/vk_textures.c
=> Fix traditional render tries to load bluenoise
