w23/xash3d-fwgs

ref_vk/shaders/rtx.comp

Modulate the subsequent bounces with texture color. This makes it
consistent with the way surface lights and dlights work.

rtx: presumably fix gray textures

---

ref_vk/TODO.md
ref_vk/vk_brush.c

make all geoms share the same constant vertex offset so that continuous indices can be exploited to generate only a single draw call for a group of geometries with the same texture

concat brush drawcalls

---

ref_vk/vk_beams.c
ref_vk/vk_brush.c
ref_vk/vk_ray_model.c
ref_vk/vk_render.h
ref_vk/vk_sprite.c
ref_vk/vk_studio.c

after we've updated how brush index buffer references vertices to allow
for draw call coalescing ray tracing broke on amd.
this is because amd cards expect a correct value in
VkAccelerationStructureGeometryTrianglesDataKHR::maxVertex. make sure we
fill a correct value there.

rtx: calculate maxVertex correctly

---

ref_vk/vk_framectl.c

make sure that we use host_cached memory, otherwise device_local will be picked by default, which is very slow to read from.

improve screenshot performance, fix #87

---

ref_vk/vk_rtx.c

Fixes #167. Textures are still blurry when viewed at an angle as
UVDerivsFromRayCone does not take anisotropy into account.

Convert fov to radians when computing pixel cone.

---

engine/common/com_strings.h

One line pr adding vulkan render into render's list. This is an addition to [this PR from NightFox](https://github.com/w23/xash3d-fwgs/pull/244) and mandatory patches for [this PR in mainui to work](https://github.com/FWGS/mainui_cpp/pull/66)

Add vk render to video modes

---

ref_vk/vk_core.c

Previously, in order for rtx mode to work, it was necessary to specify the appropriate flag in the command line arguments. Don't have to do this, in any case we go through all the video cards and check RTX support

Remove -rtx flag

---

ref_vk/dumbspter.c
ref_vk/vk_light.c

apparently model_t->leafs goes from 1 to model_t->numleafs, not from 0
to model_t->numleafs-1

rtx: fix skipping the last leaf when clustering lights, fix #97

---

ref_vk/vk_brush.c
ref_vk/vk_light.c
ref_vk/vk_scene.c

Does not yet reload emissive patches ("_light" argument for surfaces).
Does not reload deleted surfaces.

patch: enable live reloading, fix #281

---

ref_vk/camera.c
ref_vk/infotool.c
ref_vk/vk_light.c
ref_vk/vk_light.h

Do not skip 0th leaf when iterating through R_FatPVS results.
Also:
- move infotool from camera.c to infotool.c
- add hit coords to infotool
- add limited light clusters info into infotool
- add a bit more debug info to light clusters
fixes #279

rtx: fix moving emissive surfaces light clusters

---

ref_vk/vk_sprite.c

Теперь спрайты плавно затухают как и должны, правильная полупрозрачность у выстрелов гаус пушки и т. п.

fix tr.blend (fade fx) for sprites

---

ref_vk/TODO.md
ref_vk/alolcator.c
ref_vk/alolcator.h
ref_vk/vk_beams.c
ref_vk/vk_brush.c
ref_vk/vk_const.h
ref_vk/vk_framectl.c
ref_vk/vk_render.c
ref_vk/vk_render.h
ref_vk/vk_scene.c
ref_vk/vk_sprite.c
ref_vk/vk_studio.c
ref_vk/wscript

- Clear split between static and dynamic geometry within the same buffer
- Store previous frame geometry data longer
- Use simpler ring buffer for allocation
- Add waf unit tests for alolcator
Known issues:
- ray tracing still glitches a lot

vk: ring-based dynamic geometry buf alloc

---

ref_vk/shaders/light.glsl
ref_vk/shaders/light_polygon.glsl
ref_vk/shaders/ray_interop.h
ref_vk/vk_framectl.c
ref_vk/vk_light.c
ref_vk/vk_light.h
ref_vk/vk_rtx.c

Ends up uploading only a few megs per frame, spread across a hundred or so ranges on average.
Still not great, now validation is too slow. But otherwise it's back to ~60fps.
I think it's end of the line for this approach. Even betterer light clusters would need a complete overhaul, e.g. being moved completely to GPU compute.
Fixes #385

Upload only dirty light clusters regions

---

.github/workflows/c-cpp.yml
ref/vk/vk_core.c
ref/vk/vk_core.h
ref/vk/vk_nv_aftermath.c
ref/vk/vk_nv_aftermath.h
scripts/gha/deps_linux.sh
scripts/gha/deps_win32.sh

make nv_checkpoint not depend on rt
split it logically from aftermath
don't crash when this extension is not available

vk: change how device extensions are checked

---

ref/vk/vk_core.c
ref/vk/vk_core.h
ref/vk/vk_descriptor.c
ref/vk/vk_rtx.c
ref/vk/vk_textures.c
ref/vk/vk_textures.h

Use these flags to pick the right sampler. Fixes issues with blurry and leaking fonts, main menu tiles lines, etc
fixes #439, fixes #79

vk: respect TF_NEAREST/CLAMP/BORDER flags

---

ref/vk/NOTES.md
ref/vk/profiler.h
ref/vk/r_slows.c
ref/vk/r_slows.h
ref/vk/vk_common.h
ref/vk/vk_core.c
ref/vk/vk_core.h
ref/vk/vk_cvar.c
ref/vk/vk_cvar.h
ref/vk/vk_framectl.c
ref/vk/vk_framectl.h
ref/vk/vk_querypool.c
ref/vk/vk_querypool.h
ref/vk/vk_render.c
ref/vk/vk_rmain.c
ref/vk/vk_staging.c
ref/vk/vk_studio.c
ref/vk/vk_swapchain.c

- ~(2) Basic counters: brush models, studio models, BLASes, sprites, beams, lights (static+dynamic, polygons and vertices), data sizes and rates, staging uploads counts, etc.~
- -> #483 
- ~(4) GPU usage info~
- -> #484
- ~GPU timestamp markers/scopes~
- -> #485
- ~Graphs for all metrics~
- ~Percentiles for all metrics~
- ~Graphs for metric percentiles~
- -> #486 
- ~Export to chrome://trace or other similar formats~
- -> #487 
Fixes #412

vk: start refactoring profiler

---

ref/vk/r_speeds.c
ref/vk/vk_common.h
ref/vk/vk_triapi.c

vk: profiler: start implementing universal metric graphs

---

ref/vk/shaders/bounce.comp
ref/vk/shaders/light_common.glsl
ref/vk/shaders/ray_primary.comp

de_cbble contains a bunch of floating boxes, which makes sunlight leak if internal back-facing surfaces are culled.
Generally, we should not be culling ray traced triangles (unless absolutely necessary for correctness), as it makes the shader perform additional unnecessary checks.
Try disabling culling universally and see whether it breaks anything.
Fixes #507

rt: don't cull c/cw triangles to fix shadow leaks

---

ref/vk/vk_ray_internal.h
ref/vk/vk_ray_model.c
ref/vk/vk_rtx.c

It's been obsolete and broken for many months now.
Fixes #509

rt: remove freeze_models functionality

---

ref/vk/vk_brush.c
ref/vk/vk_mapents.c
ref/vk/vk_mapents.h
ref/vk/vk_render.c
ref/vk/vk_scene.c

Make func_wall lights static, and also allow patching their offsets

---

.github/workflows/c-cpp.yml

It started failing suddenly w/o any changes on our part. It is irrelevant for this fork, so disable it for now.

ci: temporarily disable the nswitch target

---

ref/vk/NOTES.md
ref/vk/vk_core.c
ref/vk/vk_entity_data.c
ref/vk/vk_entity_data.h
ref/vk/vk_materials.c
ref/vk/vk_rmain.c
ref/vk/vk_scene.c
ref/vk/vk_studio.c
ref/vk/vk_studio.h
ref/vk/vk_studio_model.c
ref/vk/vk_studio_model.h

META WIP even less stable and more experimental changes to studio model tracking

---

ref/vk/shaders/denoiser.comp
ref/vk/shaders/ray_primary.comp
ref/vk/vk_brush.c
ref/vk/vk_mapents.c
ref/vk/vk_mapents.h

Smooth normals between selected brush surfaces if the angle between them is small enough.
Fixes #139, supersedes #348

Smooth brush surface normals

---

ref/vk/vk_framectl.c
ref/vk/vk_overlay.c
ref/vk/vk_overlay.h
ref/vk/vk_render.c
ref/vk/vk_render.h
ref/vk/vk_rtx.c
ref/vk/vk_swapchain.c

On Windows we're seeing a max size = 0x0 swapchains. Those cannot be created or used. Make sure that we're not, and we're not trying to draw anything when there's no swapchain available.
Unfortunately we still have to call some rendering functions (without actually rendering anything) to make sure that various invariants hold.
fixes #463

vk: do not draw into empty swapchain

---

ref/vk/vk_studio_model.c
ref/vk/vk_studio_model.h

python/357 has bullets submodels which are animated using parent bones. Their direct bones are static, and thus the entire submodel was picked up as static.
Now when computing bone transform for particular sequence/anim frame also merge it with parent transform. Bones are laid out sequentially in their "dependency order" so using a direct parent is fine, as it also contains its parent transforms.
Fixes: #554

vk: studio: do not ignore parent bones when detecting static submodels

---

ref/vk/alolcator.c
ref/vk/vk_ray_accel.c
ref/vk/vk_ray_internal.h
ref/vk/vk_scene.c
ref/vk/vk_sprite.c
ref/vk/vk_studio.c
ref/vk/vk_studio_model.c

Fixes made during stream E295

---

ref/vk/profiler.h
ref/vk/r_speeds.c
ref/vk/r_speeds.h

Fix source locations for scopes in `r_speeds_list_metrics` as described in Issue #542. 
Also slightly simplify metrics list print formatting and add an option to print it as a table. It can be turned on/off via cvar `r_speeds_metrics_as_table`. 
This does not look very good in HL itself because it uses non-monospace font by default in console, but it looks much cleaner and readable in console and log file output.

vk: profiler: fix source locations for scopes (#542)

---

ref/vk/vk_materials.c
ref/vk/vk_materials.h
ref/vk/vk_studio.c

With deprecation of `set` flag, roughness was always replaced on studio model chome textures.

vk: fix roughness on studio model chrome textures

---

ref/vk/r_speeds.c
ref/vk/vk_rtx.c

This is not a valid reason to assert/crash, even though it is clearly a programming mistake. If the stack is corrupted, just print its contents as an S_ERROR and continue.
Also:
- Fix the ultimate reason for stack being unbalanced for #604
- Do not analyze scopes when not needed, i.e. when `r_speeds` is zero.
Fixes #604

vk: do not crash on corrupted scopes stack

---

ref/vk/TODO.md
ref/vk/data/valve/luchiki/maps/c1a1b.patch
ref/vk/shaders/denoiser.comp
ref/vk/vk_brush.c
ref/vk/vk_mapents.c
ref/vk/vk_mapents.h

Uses `_xvk_smoothing_excluded` field.
Surfaces can still be smoothed with a limited list of neightbours explicitly by being included in a smoothing group.
Fixes #619

vk: add a mechanism for exclusion of single surfaces from smoothing

---

ref/vk/shaders/denoiser.comp
ref/vk/vk_studio.c

It was using old pre-transform values for prev_verts, and that was confusing temporal denoiser.
We should bone-transform vertices first, and only then store them as prev_verts.
Fixes #585

vk: fix weird lines on suit studio model

---

ref/vk/TODO.md
ref/vk/vk_brush.c
ref/vk/vk_descriptor.c

When texture coordinates are inverted, it makes tangent look into oppsite direction, which inverts TBN and therefore normal map.
Make sure the tangent points to a consistent direction.
Fixes #627

vk: fix occasional inverted normal maps

---

ref/vk/NOTES.md
ref/vk/TODO.md
ref/vk/shaders/bounce.comp
ref/vk/shaders/ray_primary.comp
ref/vk/vk_brush.c
ref/vk/vk_ray_accel.c

E328-E330: Improve backface culling

---

engine/common/imagelib/img_ktx2.c
engine/common/imagelib/img_main.c
engine/common/imagelib/img_utils.c
ref/vk/NOTES.md
ref/vk/TODO.md
ref/vk/data/valve/luchiki/maps/c2a5.patch
ref/vk/r_speeds.c
ref/vk/r_textures.c
ref/vk/r_textures.h
ref/vk/shaders/ray_interop.h
ref/vk/shaders/ray_primary.comp
ref/vk/shaders/ray_primary.rchit
ref/vk/shaders/ray_primary_hit.glsl
ref/vk/stringview.c
ref/vk/stringview.h
ref/vk/vk_brush.c
ref/vk/vk_common.h
ref/vk/vk_logs.c
ref/vk/vk_mapents.c
ref/vk/vk_mapents.h
ref/vk/vk_rmain.c
ref/vk/vk_rtx.c
ref/vk/vk_rtx.h
ref/vk/vk_scene.c
ref/vk/vk_textures.c
ref/vk/vk_textures.h

Skybox improvements (E346-E347)

---

ref/vk/NOTES.md
ref/vk/TODO.md
ref/vk/shaders/bounce.comp
ref/vk/shaders/denoiser.comp
ref/vk/shaders/ray_primary.comp
ref/vk/shaders/rt_geometry.glsl
ref/vk/shaders/trace_simple_blending.glsl
ref/vk/vk_brush.c
ref/vk/vk_ray_accel.c
ref/vk/vk_ray_internal.h
ref/vk/vk_ray_model.c
ref/vk/vk_render.c
ref/vk/vk_render.h
ref/vk/vk_rtx.h
ref/vk/vk_sprite.c
ref/vk/vk_studio.c

Stuff done during streams E352-E354

---

ref/vk/shaders/ray_primary_hit.glsl

Stuff done during stream E355

---

ref/vk/vk_ray_accel.c
ref/vk/vk_ray_model.c

Once upon a time, there were some BLASes. There were the BLASes for dynamic geometry, that were to be used every frame to draw very dynamic things, like sprites and beams. They were initialized at the very begining of the renderer's lifetime, and were expected to live happily for the entire process duration. However, an evil NewMap appeared. It didn't care abount anything or anyone, so when it came, it just cleared all the allocators, and allowed other BLASes to be allocated into the same space as dynamic BLASes were already given. This made BLASes live on top of each other, use each others toys and make them fight. They weren't happy.
So we just kill them and creat them again from scratch, when the evil NewMap comes.
The end.
Fixes #729

vk: rt: add workaround for holes in geometry

---

ref/vk/shaders/bounce.comp
ref/vk/shaders/denoiser.comp
ref/vk/shaders/denoiser_config.glsl
ref/vk/shaders/denoiser_utils.glsl
ref/vk/shaders/diffuse_gi_sh_atrous.glsl
ref/vk/shaders/diffuse_gi_sh_denoise_init.comp
ref/vk/shaders/diffuse_gi_sh_denoise_pass_1.comp
ref/vk/shaders/diffuse_gi_sh_denoise_pass_2.comp
ref/vk/shaders/diffuse_gi_sh_denoise_pass_3.comp
ref/vk/shaders/diffuse_gi_sh_denoise_pass_4.comp
ref/vk/shaders/diffuse_gi_sh_denoise_pass_5.comp
ref/vk/shaders/diffuse_gi_sh_denoise_save.comp
ref/vk/shaders/indirect_diffuse_atrous1.comp
ref/vk/shaders/ray_interop.h
ref/vk/shaders/rt.json
ref/vk/shaders/spherical_harmonics.glsl
ref/vk/vk_cvar.c
ref/vk/vk_cvar.h
ref/vk/vk_descriptor.c
ref/vk/vk_devmem.c
ref/vk/vk_meatpipe.c
ref/vk/vk_rtx.c

For enabling new denoising method use cvars:
rt_denoise_gi_by_sh 1
Enable denoising global illumination by Quake 2 algorythm (spherical harmonics)
rt_only_diffuse_gi 1
Blend diffuse and specular indirect lighting for cleaner image (reflections denoising will be in future with other algorythm)

Denoise diffuse indirect lighting
